 * NUMPY ARRAYS 


In [2]:
#Cast a list to a 1D array
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
#Shortcut 
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
#2D array
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#Making arrays of only specific numbers
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
#To get evenly spaced points
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
"""array([ IS  A 1D ARRAY AS IT HAS ONLY 1[.array([[ IS A 2D ARRAY """

'array([ IS  A 1D ARRAY AS IT HAS ONLY 1[.array([[ IS A 2D ARRAY '

In [15]:
##To create identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
##1D array with uniformly distributed random nos. btw 0 and 1
np.random.rand(5)

array([0.10239628, 0.34430404, 0.29405697, 0.2891244 , 0.38905904])

In [18]:
np.random.rand(3,3)  #for 2D matrix

array([[0.16843638, 0.55095719, 0.85995743],
       [0.24938329, 0.26122017, 0.94074328],
       [0.48879387, 0.49796641, 0.11284717]])

In [19]:
#For std.normal distribution
np.random.randn(2)

array([ 0.00315023, -0.31759034])

In [20]:
np.random.randn(4,5) #This isn't a tuple.Its each dimension as a separate argument

array([[-0.47213095,  1.18329128,  0.98965159,  1.00127513,  0.70372073],
       [ 1.63744328,  0.02081143, -0.40708016,  2.42532696, -0.19526   ],
       [ 0.32194391, -1.55302688, -1.35960601,  0.49563538, -0.33959711],
       [ 0.05785947, -0.2086158 ,  0.82373796, -0.56582486, -0.97066094]])

In [21]:
#Random int generation
np.random.randint(0,50,3)

array([23,  7, 37])

In [22]:
#Reshape array to matrix
arr = np.arange(25)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
arr.reshape(5,5) #No.of rows x columns == no.elements of array,else error shown (5 x 5 = 25)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
ranarr = np.random.randint(0,50,10)

In [28]:
ranarr

array([ 3,  3, 15, 35, 13, 42, 34, 35, 14,  5])

In [29]:
ranarr.max()

42

In [30]:
ranarr.min()

3

In [31]:
#Finding index location of max and min elements
ranarr.argmax()

5

In [32]:
ranarr.argmin()

0

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
arr.shape

(25,)

In [38]:
arr.dtype

dtype('int32')

* NUMPY INDEXING AND SELECTION 

In [39]:
arr = np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[8]

8

In [42]:
arr[1:5]

array([1, 2, 3, 4])

In [43]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [44]:
#Value broadcasting
arr[0:5] = 150

In [45]:
arr

array([150, 150, 150, 150, 150,   5,   6,   7,   8,   9,  10])

In [46]:
arr = np.arange(0,11)

In [47]:
slice = arr[0:6]

In [48]:
slice

array([0, 1, 2, 3, 4, 5])

In [49]:
slice[:] = 123

In [50]:
slice

array([123, 123, 123, 123, 123, 123])

In [51]:
arr   #Value is chaged here too(its a reference not a copy)

array([123, 123, 123, 123, 123, 123,   6,   7,   8,   9,  10])

In [52]:
arrc = arr.copy()

In [53]:
arrc[:] = 153

In [54]:
arrc

array([153, 153, 153, 153, 153, 153, 153, 153, 153, 153, 153])

In [55]:
arr  #Now its not a reference.Only copy has been changed

array([123, 123, 123, 123, 123, 123,   6,   7,   8,   9,  10])

In [56]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [57]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [58]:
#Double Bracket method
arr_2d[1][2]

30

In [59]:
#Single Bracket with comma method
arr_2d[1,2]

30

In [60]:
#Slicing to get top right corner here
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
"""CONDITIONAL SELECTON"""

In [90]:
arr = np.arange(1,11)

In [63]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
bool_arr = arr>5

In [71]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [73]:
arr[bool_arr]  #Conditional selction of only true ones

array([ 6,  7,  8,  9, 10])

In [74]:
#Shortcut
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [75]:
#Array with array operations
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [79]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr * arr  #can add,sub,mul,div

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [88]:
#Array with scalars
arr + 100

array([100, 101, 102, 103, 104, 105])

In [91]:
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [84]:
arr = np.arange(0,6)

In [85]:
arr

array([0, 1, 2, 3, 4, 5])

In [86]:
arr / arr #notice first element must return 0/0 err but we only get warning in numpy

C:\Users\Hariharan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.])

In [92]:
np.sqrt(arr) #similarly exp,max,min

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [93]:
np.sin(arr) #log,cos... 

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [95]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])